// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package shipyard

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_DATA           MessageType = 0
	MessageType_NEW_CONNECTION MessageType = 1
	MessageType_WRITE_DONE     MessageType = 2
	MessageType_READ_DONE      MessageType = 3
	MessageType_ERROR          MessageType = 4
)

var MessageType_name = map[int32]string{
	0: "DATA",
	1: "NEW_CONNECTION",
	2: "WRITE_DONE",
	3: "READ_DONE",
	4: "ERROR",
}

var MessageType_value = map[string]int32{
	"DATA":           0,
	"NEW_CONNECTION": 1,
	"WRITE_DONE":     2,
	"READ_DONE":      3,
	"ERROR":          4,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

type NullResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullResponse) Reset()         { *m = NullResponse{} }
func (m *NullResponse) String() string { return proto.CompactTextString(m) }
func (*NullResponse) ProtoMessage()    {}
func (*NullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *NullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullResponse.Unmarshal(m, b)
}
func (m *NullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullResponse.Marshal(b, m, deterministic)
}
func (m *NullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullResponse.Merge(m, src)
}
func (m *NullResponse) XXX_Size() int {
	return xxx_messageInfo_NullResponse.Size(m)
}
func (m *NullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NullResponse proto.InternalMessageInfo

type OpenData struct {
	ServiceId            string      `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	RequestId            string      `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Location             string      `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Type                 MessageType `protobuf:"varint,4,opt,name=type,proto3,enum=shipyard.MessageType" json:"type,omitempty"`
	Data                 []byte      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OpenData) Reset()         { *m = OpenData{} }
func (m *OpenData) String() string { return proto.CompactTextString(m) }
func (*OpenData) ProtoMessage()    {}
func (*OpenData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *OpenData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenData.Unmarshal(m, b)
}
func (m *OpenData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenData.Marshal(b, m, deterministic)
}
func (m *OpenData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenData.Merge(m, src)
}
func (m *OpenData) XXX_Size() int {
	return xxx_messageInfo_OpenData.Size(m)
}
func (m *OpenData) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenData.DiscardUnknown(m)
}

var xxx_messageInfo_OpenData proto.InternalMessageInfo

func (m *OpenData) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *OpenData) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *OpenData) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *OpenData) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_DATA
}

func (m *OpenData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExposeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Matches              []*Match `protobuf:"bytes,4,rep,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExposeRequest) Reset()         { *m = ExposeRequest{} }
func (m *ExposeRequest) String() string { return proto.CompactTextString(m) }
func (*ExposeRequest) ProtoMessage()    {}
func (*ExposeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *ExposeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExposeRequest.Unmarshal(m, b)
}
func (m *ExposeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExposeRequest.Marshal(b, m, deterministic)
}
func (m *ExposeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExposeRequest.Merge(m, src)
}
func (m *ExposeRequest) XXX_Size() int {
	return xxx_messageInfo_ExposeRequest.Size(m)
}
func (m *ExposeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExposeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExposeRequest proto.InternalMessageInfo

func (m *ExposeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExposeRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ExposeRequest) GetMatches() []*Match {
	if m != nil {
		return m.Matches
	}
	return nil
}

type ExposeResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExposeResponse) Reset()         { *m = ExposeResponse{} }
func (m *ExposeResponse) String() string { return proto.CompactTextString(m) }
func (*ExposeResponse) ProtoMessage()    {}
func (*ExposeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *ExposeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExposeResponse.Unmarshal(m, b)
}
func (m *ExposeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExposeResponse.Marshal(b, m, deterministic)
}
func (m *ExposeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExposeResponse.Merge(m, src)
}
func (m *ExposeResponse) XXX_Size() int {
	return xxx_messageInfo_ExposeResponse.Size(m)
}
func (m *ExposeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExposeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExposeResponse proto.InternalMessageInfo

func (m *ExposeResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DestroyRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyRequest) Reset()         { *m = DestroyRequest{} }
func (m *DestroyRequest) String() string { return proto.CompactTextString(m) }
func (*DestroyRequest) ProtoMessage()    {}
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *DestroyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyRequest.Unmarshal(m, b)
}
func (m *DestroyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyRequest.Marshal(b, m, deterministic)
}
func (m *DestroyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyRequest.Merge(m, src)
}
func (m *DestroyRequest) XXX_Size() int {
	return xxx_messageInfo_DestroyRequest.Size(m)
}
func (m *DestroyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyRequest proto.InternalMessageInfo

func (m *DestroyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoteRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteRequest) Reset()         { *m = RemoteRequest{} }
func (m *RemoteRequest) String() string { return proto.CompactTextString(m) }
func (*RemoteRequest) ProtoMessage()    {}
func (*RemoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *RemoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteRequest.Unmarshal(m, b)
}
func (m *RemoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteRequest.Marshal(b, m, deterministic)
}
func (m *RemoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteRequest.Merge(m, src)
}
func (m *RemoteRequest) XXX_Size() int {
	return xxx_messageInfo_RemoteRequest.Size(m)
}
func (m *RemoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteRequest proto.InternalMessageInfo

type Match struct {
	Http                 *Http    `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	GRPC                 *Grpc    `protobuf:"bytes,2,opt,name=gRPC,proto3" json:"gRPC,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Match) Reset()         { *m = Match{} }
func (m *Match) String() string { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()    {}
func (*Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Match.Unmarshal(m, b)
}
func (m *Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Match.Marshal(b, m, deterministic)
}
func (m *Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Match.Merge(m, src)
}
func (m *Match) XXX_Size() int {
	return xxx_messageInfo_Match.Size(m)
}
func (m *Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Match proto.InternalMessageInfo

func (m *Match) GetHttp() *Http {
	if m != nil {
		return m.Http
	}
	return nil
}

func (m *Match) GetGRPC() *Grpc {
	if m != nil {
		return m.GRPC
	}
	return nil
}

type Http struct {
	Headers              []*Header `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Http) Reset()         { *m = Http{} }
func (m *Http) String() string { return proto.CompactTextString(m) }
func (*Http) ProtoMessage()    {}
func (*Http) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{7}
}

func (m *Http) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http.Unmarshal(m, b)
}
func (m *Http) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http.Marshal(b, m, deterministic)
}
func (m *Http) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http.Merge(m, src)
}
func (m *Http) XXX_Size() int {
	return xxx_messageInfo_Http.Size(m)
}
func (m *Http) XXX_DiscardUnknown() {
	xxx_messageInfo_Http.DiscardUnknown(m)
}

var xxx_messageInfo_Http proto.InternalMessageInfo

func (m *Http) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

type Header struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Exact                string   `protobuf:"bytes,2,opt,name=exact,proto3" json:"exact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{8}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Header) GetExact() string {
	if m != nil {
		return m.Exact
	}
	return ""
}

type Grpc struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Grpc) Reset()         { *m = Grpc{} }
func (m *Grpc) String() string { return proto.CompactTextString(m) }
func (*Grpc) ProtoMessage()    {}
func (*Grpc) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{9}
}

func (m *Grpc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grpc.Unmarshal(m, b)
}
func (m *Grpc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grpc.Marshal(b, m, deterministic)
}
func (m *Grpc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grpc.Merge(m, src)
}
func (m *Grpc) XXX_Size() int {
	return xxx_messageInfo_Grpc.Size(m)
}
func (m *Grpc) XXX_DiscardUnknown() {
	xxx_messageInfo_Grpc.DiscardUnknown(m)
}

var xxx_messageInfo_Grpc proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("shipyard.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*NullResponse)(nil), "shipyard.NullResponse")
	proto.RegisterType((*OpenData)(nil), "shipyard.OpenData")
	proto.RegisterType((*ExposeRequest)(nil), "shipyard.ExposeRequest")
	proto.RegisterType((*ExposeResponse)(nil), "shipyard.ExposeResponse")
	proto.RegisterType((*DestroyRequest)(nil), "shipyard.DestroyRequest")
	proto.RegisterType((*RemoteRequest)(nil), "shipyard.RemoteRequest")
	proto.RegisterType((*Match)(nil), "shipyard.Match")
	proto.RegisterType((*Http)(nil), "shipyard.Http")
	proto.RegisterType((*Header)(nil), "shipyard.Header")
	proto.RegisterType((*Grpc)(nil), "shipyard.Grpc")
}

func init() {
	proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7)
}

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xdb, 0x6e, 0xda, 0x40,
	0x10, 0xad, 0x89, 0x49, 0x60, 0x00, 0xc7, 0x9a, 0xde, 0x2c, 0xa4, 0x4a, 0xc8, 0x4f, 0x24, 0x0f,
	0xa8, 0x72, 0xbf, 0x00, 0x81, 0x45, 0x91, 0x5a, 0xbb, 0xda, 0x52, 0xe5, 0x11, 0x6d, 0xec, 0x51,
	0x40, 0x02, 0xef, 0xd6, 0xbb, 0xa9, 0xc2, 0xf7, 0xf4, 0xa7, 0xfa, 0x39, 0xd5, 0xae, 0xed, 0x00,
	0x6d, 0xde, 0x76, 0xe7, 0x9c, 0xd9, 0x39, 0x33, 0x67, 0x16, 0xfa, 0x8a, 0xca, 0x5f, 0x54, 0x4e,
	0x64, 0x29, 0xb4, 0xc0, 0x8e, 0xda, 0x6c, 0xe5, 0x81, 0x97, 0x79, 0xe8, 0x41, 0x3f, 0x79, 0xdc,
	0xed, 0x18, 0x29, 0x29, 0x0a, 0x45, 0xe1, 0x6f, 0x07, 0x3a, 0xa9, 0xa4, 0x62, 0xce, 0x35, 0xc7,
	0x0f, 0x00, 0x26, 0x6d, 0x9b, 0xd1, 0x7a, 0x9b, 0x07, 0xce, 0xc8, 0x19, 0x77, 0x59, 0xb7, 0x8e,
	0x2c, 0x73, 0x03, 0x97, 0xf4, 0xf3, 0x91, 0x94, 0x36, 0x70, 0xab, 0x82, 0xeb, 0xc8, 0x32, 0xc7,
	0x21, 0x74, 0x76, 0x22, 0xe3, 0x7a, 0x2b, 0x8a, 0xe0, 0xc2, 0x82, 0xcf, 0x77, 0xbc, 0x01, 0x57,
	0x1f, 0x24, 0x05, 0xee, 0xc8, 0x19, 0x7b, 0xd1, 0xdb, 0x49, 0xa3, 0x67, 0xf2, 0x95, 0x94, 0xe2,
	0x0f, 0xb4, 0x3a, 0x48, 0x62, 0x96, 0x82, 0x08, 0x6e, 0xce, 0x35, 0x0f, 0xda, 0x23, 0x67, 0xdc,
	0x67, 0xf6, 0x1c, 0xde, 0xc3, 0x20, 0x7e, 0x92, 0x42, 0x11, 0xab, 0xaa, 0x19, 0x52, 0xc1, 0xf7,
	0x54, 0x6b, 0xb4, 0x67, 0x13, 0x93, 0xa2, 0xd4, 0x56, 0x58, 0x9b, 0xd9, 0x33, 0xde, 0xc0, 0xd5,
	0x9e, 0xeb, 0x6c, 0x43, 0x2a, 0x70, 0x47, 0x17, 0xe3, 0x5e, 0x74, 0x7d, 0x52, 0xda, 0x00, 0xac,
	0xc1, 0xc3, 0x11, 0x78, 0x4d, 0x8d, 0x6a, 0x36, 0xe8, 0x41, 0xeb, 0x79, 0x0c, 0xad, 0x6d, 0x6e,
	0x18, 0x73, 0x52, 0xba, 0x14, 0x87, 0x46, 0xc6, 0xbf, 0x8c, 0x6b, 0x18, 0x30, 0xda, 0x0b, 0xdd,
	0xe8, 0x0c, 0x53, 0x68, 0xdb, 0x32, 0x18, 0x82, 0xbb, 0xd1, 0x5a, 0x5a, 0x6e, 0x2f, 0xf2, 0x8e,
	0x2a, 0x3e, 0x6b, 0x2d, 0x99, 0xc5, 0x0c, 0xe7, 0x81, 0x7d, 0x9b, 0xd9, 0x06, 0xce, 0x38, 0x8b,
	0x52, 0x66, 0xcc, 0x62, 0x61, 0x04, 0xae, 0xc9, 0xc0, 0x5b, 0xb8, 0xda, 0x10, 0xcf, 0xa9, 0x54,
	0x81, 0x63, 0x1b, 0xf3, 0x4f, 0x9e, 0xb4, 0x00, 0x6b, 0x08, 0x61, 0x04, 0x97, 0x55, 0xe8, 0xc5,
	0xb1, 0xbd, 0x81, 0x36, 0x3d, 0xf1, 0x4c, 0xd7, 0x86, 0x56, 0x97, 0xf0, 0x12, 0x5c, 0x53, 0xf5,
	0xf6, 0x07, 0xf4, 0x4e, 0x2c, 0xc2, 0x0e, 0xb8, 0xf3, 0xe9, 0x6a, 0xea, 0xbf, 0x42, 0x04, 0x2f,
	0x89, 0xef, 0xd6, 0xb3, 0x34, 0x49, 0xe2, 0xd9, 0x6a, 0x99, 0x26, 0xbe, 0x83, 0x1e, 0xc0, 0x1d,
	0x5b, 0xae, 0xe2, 0xf5, 0x3c, 0x4d, 0x62, 0xbf, 0x85, 0x03, 0xe8, 0xb2, 0x78, 0x3a, 0xaf, 0xae,
	0x17, 0xd8, 0x85, 0x76, 0xcc, 0x58, 0xca, 0x7c, 0x37, 0xfa, 0xe3, 0x80, 0x5f, 0x4d, 0x6a, 0x26,
	0x8a, 0x82, 0x32, 0xbb, 0x24, 0x11, 0xb8, 0x66, 0x15, 0x11, 0x8f, 0xad, 0x34, 0xab, 0x39, 0x7c,
	0x21, 0x36, 0x76, 0x3e, 0x3a, 0xb8, 0x00, 0xac, 0x5c, 0xfb, 0x22, 0x32, 0xbe, 0xfb, 0x5e, 0xed,
	0x2a, 0xbe, 0x3f, 0xb2, 0xcf, 0xf6, 0x66, 0x18, 0xfc, 0x0f, 0xd4, 0x66, 0x2f, 0xe0, 0x75, 0x6d,
	0xee, 0xd9, 0x4b, 0x27, 0x09, 0xe7, 0xde, 0x0f, 0xdf, 0x1d, 0x91, 0xd3, 0x1f, 0x75, 0x7f, 0x69,
	0xbf, 0xdc, 0xa7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xed, 0x3f, 0x88, 0x70, 0x82, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RemoteConnectionClient is the client API for RemoteConnection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteConnectionClient interface {
	// Open a stream to the remote TCP port
	Open(ctx context.Context, opts ...grpc.CallOption) (RemoteConnection_OpenClient, error)
	// Open a new TCP port for the local service on the server and start listening
	ExposeLocalService(ctx context.Context, in *ExposeRequest, opts ...grpc.CallOption) (*ExposeResponse, error)
	// Close the remote TCP port and remove all resources
	DestroyLocalService(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*NullResponse, error)
}

type remoteConnectionClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteConnectionClient(cc grpc.ClientConnInterface) RemoteConnectionClient {
	return &remoteConnectionClient{cc}
}

func (c *remoteConnectionClient) Open(ctx context.Context, opts ...grpc.CallOption) (RemoteConnection_OpenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RemoteConnection_serviceDesc.Streams[0], "/shipyard.RemoteConnection/Open", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteConnectionOpenClient{stream}
	return x, nil
}

type RemoteConnection_OpenClient interface {
	Send(*OpenData) error
	Recv() (*OpenData, error)
	grpc.ClientStream
}

type remoteConnectionOpenClient struct {
	grpc.ClientStream
}

func (x *remoteConnectionOpenClient) Send(m *OpenData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *remoteConnectionOpenClient) Recv() (*OpenData, error) {
	m := new(OpenData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *remoteConnectionClient) ExposeLocalService(ctx context.Context, in *ExposeRequest, opts ...grpc.CallOption) (*ExposeResponse, error) {
	out := new(ExposeResponse)
	err := c.cc.Invoke(ctx, "/shipyard.RemoteConnection/ExposeLocalService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteConnectionClient) DestroyLocalService(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*NullResponse, error) {
	out := new(NullResponse)
	err := c.cc.Invoke(ctx, "/shipyard.RemoteConnection/DestroyLocalService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteConnectionServer is the server API for RemoteConnection service.
type RemoteConnectionServer interface {
	// Open a stream to the remote TCP port
	Open(RemoteConnection_OpenServer) error
	// Open a new TCP port for the local service on the server and start listening
	ExposeLocalService(context.Context, *ExposeRequest) (*ExposeResponse, error)
	// Close the remote TCP port and remove all resources
	DestroyLocalService(context.Context, *DestroyRequest) (*NullResponse, error)
}

// UnimplementedRemoteConnectionServer can be embedded to have forward compatible implementations.
type UnimplementedRemoteConnectionServer struct {
}

func (*UnimplementedRemoteConnectionServer) Open(srv RemoteConnection_OpenServer) error {
	return status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (*UnimplementedRemoteConnectionServer) ExposeLocalService(ctx context.Context, req *ExposeRequest) (*ExposeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExposeLocalService not implemented")
}
func (*UnimplementedRemoteConnectionServer) DestroyLocalService(ctx context.Context, req *DestroyRequest) (*NullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyLocalService not implemented")
}

func RegisterRemoteConnectionServer(s *grpc.Server, srv RemoteConnectionServer) {
	s.RegisterService(&_RemoteConnection_serviceDesc, srv)
}

func _RemoteConnection_Open_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteConnectionServer).Open(&remoteConnectionOpenServer{stream})
}

type RemoteConnection_OpenServer interface {
	Send(*OpenData) error
	Recv() (*OpenData, error)
	grpc.ServerStream
}

type remoteConnectionOpenServer struct {
	grpc.ServerStream
}

func (x *remoteConnectionOpenServer) Send(m *OpenData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *remoteConnectionOpenServer) Recv() (*OpenData, error) {
	m := new(OpenData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RemoteConnection_ExposeLocalService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteConnectionServer).ExposeLocalService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipyard.RemoteConnection/ExposeLocalService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteConnectionServer).ExposeLocalService(ctx, req.(*ExposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteConnection_DestroyLocalService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteConnectionServer).DestroyLocalService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipyard.RemoteConnection/DestroyLocalService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteConnectionServer).DestroyLocalService(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteConnection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shipyard.RemoteConnection",
	HandlerType: (*RemoteConnectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExposeLocalService",
			Handler:    _RemoteConnection_ExposeLocalService_Handler,
		},
		{
			MethodName: "DestroyLocalService",
			Handler:    _RemoteConnection_DestroyLocalService_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Open",
			Handler:       _RemoteConnection_Open_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server.proto",
}
