---

name: Build
on: [push]

jobs:
  build:
    env:
      GONOSUMDB: "github.com/moby/moby"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22

      - name: Get dependencies
        run: |
          make setup
          go get -v -t ./...

      - name: Unit Test
        run: |
          make unit_test

      - name: Build
        run: |
          make snapshot

      - uses: actions/upload-artifact@v2
        with:
          name: connector
          path: |
            ./dist

  functional_test:
    name: Functional Test
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        folder: [
          './test/simple',
          './test/kubernetes',
          './test/nomad',
        ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v4.1.7
        with:
          name: connector
          path: dist

      - name: Setup Docker Multi-Arch Builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multi
          docker buildx use multi
          docker buildx inspect --bootstrap

      - name: Build and load into local Docker
        run: |
          docker buildx build --platform linux/amd64 \
          -t connector:dev \
            -f ./Dockerfile \
            ./dist \
            --load

      - name: Install Deps
        run: |
          curl https://shipyard.run/install | bash
          echo "${GITHUB_WORKSPACE}/dist/linux_amd64" >> $GITHUB_PATH
          chmod +x ${GITHUB_WORKSPACE}/dist/linux_amd64/connector

      - name: ${{ matrix.folder }}
        run: |
          cd ${{ matrix.folder }}
          shipyard test --var connector_image=connector:dev